### PR TITLE
Translate learning path into Chinese : project leader

### PR DESCRIPTION
**Pull request by node**
Refer to issue #817 

Chapter: project-leader

### CODE REVIEW

**Comment by node** [comment]
@tanzhongyi003 and @willemjiang are cordially invited to help review these translations. 😄

**Comment by rrrutledge** [comment]
Thanks for working on this, @node!  Could you move this PR over to the [InnerSourceLearningPath](https://github.com/InnerSourceCommons/InnerSourceLearningPath)?  You can see instructions on [contributing translations](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/main/CONTRIBUTING.md#translations).  Thank you!  Looking forward to it!

**Comment by node** [comment]
@rrrutledge Thanks for your guidance, I will launch a new PR in that repository after reorganizing it.

**Comment by rrrutledge** [comment]
Sounds great!  Sorry for this confusion!  I am hoping that it won't take you too much extra effort to move it over.

**Comment by node** [comment]
@rrrutledge  I have created new issue & PR : 
- Issue : https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/595
- PR(include the whole section of project leader(part01 ~ part06)): https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/596

**Pull request closed without merging**
