### PR TITLE
Adding Komyu logo in Stories page

### PR DESCRIPTION
**Pull request by tfroment**
Contribution for https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/190

### CODE REVIEW

**Review by spier — COMMENTED** [review]
@tfroment thank you for this contribution.

The article/video that we link to from the stories page is meant to provide evidence about the InnerSource approach followed at the given org. So the direct link to `https://komyu.io` might be a bit too generic for that purpose.

Do you have a link that is more specifically about InnerSource @ Komyu?

**Comment by tfroment** [comment]
Hi @spier , sure you are right, actually I mentionned initially some links in https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/190, and I ended up by putting komyu.io which is our new web site where we plan to add our own "use cases" (but they are not written yet :)... I also realize I should probably start by the "services" page as I discussed with @claredillon because Komyu is more in a situation of service provider on InnerSource  (our customers do InnerSource, and we help them) than a practionner for ourself (because we are sharing our framework in Open Source/open core model, so we have InnerSource only for some extensions of our framework...)

**Comment by spier** [comment]
Right, I see.

The same org could be both I guess:

- service provider in the field of InnerSource
- example of a company that practices InnerSource 

How do you want to proceed with this PR here? e.g.

1. change the link to something that is more specifically about InnerSource @ Komyu?
2. don't merge this PR for now, and add yourself as a service provder
3. ... other options?

**Comment by tfroment** [comment]
I believe option 2 is the best option at this step, I will then add our Inner Source use case on our web site and update the link before going back to this PR. I appologize Sebastian for the confusion, and thank you for taking the time to review this pr

**Comment by spier** [comment]
No worries at all. This is how reviews are meant to work 😃 

In this case I would even recommend to close this PR, to reduce confusion for other reviewers. You can always reopen the PR in the future or create a new one.

**Comment by tfroment** [comment]
Thank you, done

**Pull request closed without merging**
