### PR TITLE
Kpmg logo

### PR DESCRIPTION
**Pull request by OliveCannon**
KPMG logo and story

### CODE REVIEW

**Review by voborgus — CHANGES_REQUESTED** [review]
Hey Olive, this pull request currently contains not only KPMG changes, but also "InnerSource Catchup" one. Can you split them to a separate pull requests please?

**Comment by OliveCannon** [comment]
Hi @voborgus, there is something odd going on.  I only changed the KPMG on the KPMG logo update.  When I go back to the master copy the events page doesn't seem to be updated and afraid I am going to mess this up. Do you have a minute to look over it with me? thanks, Olive

**Review by voborgus — APPROVED** [review]
seems this changes already in the master branch and due to some strange reason they are appearing here. Let's skip that

**Comment by OliveCannon** [comment]
Thanks @voborgus

**Pull request merged**
