### PR TITLE
removing GitLab from Sponsors page

### PR DESCRIPTION
**Pull request by OliveCannon**
Hi Yuki, 

I have assigned this to you as I don't know who the other website maintainers are.

Thanks again for all your help!
Olive

Removal of GitLab

### CODE REVIEW

**Comment by spier** [comment]
@OliveCannon I could check the technical portion of this but I don't have the semantic context.
So could you confirm: This just means that GitLab is not sponsoring the ISC any more, right?

**Comment by OliveCannon** [comment]
HI @spier, 
yes, GitLab are not longer sponsoring InnerSource Commons so I would greatly appreciate if you could push this through.

Thanks!

**Review by spier — APPROVED** [review]
Haven't tested this locally, so fingers crossed that the Sponsors page looks ok after this change :)

**Comment by spier** [comment]
Seems to work ok. GitLab is gone from the Sponsors section, and the layout of the remaining Sponsors is fine.

Screen Shot 2023-03-16 at 8 59 44 PM

**Pull request merged**
