### PR TITLE
i18n support foundation

### LINKED ISSUE #355: Proposal for i18n support
## Proposal
The Japanese community is gradually growing, and the innersourcecommons.org page should be its landing page. Therefore, I would like to propose the internationalization of the site.

## Scope
contents, menus and footers.
However, details and reports of past events and Learning Path will be excluded from this translation

## Where to start
We would like to translate the Japanese page first. However, if this is done well, the site will be able to be translated easily into other languages as well. We will try Japanese first as an experiment, and then will try to onboard other languages if there is someone who are willing to volunteer.

Some people in InnerSource Commons Japan will participate in the work, so I want to put the repository in an easy-to-understand place. If possible, it would be useful for me to have write permission for the repo. But I don't want to break the environment since I don't yet know some of the things on the innersourcecommmons.org page. (Well, I won't be committing to the main branch for the near future, so I think I'll be fine.)
But I know there is governance in managing innersourcecommons/innersourcecommmons.org, so if there is a proper way to do it, please let me know sometimes...

I'm currently working on a repository at yuhattor/innersourcecommons.org.
We believe that a Japanese page is essential for the Japanese community. The amount of translation is not so large, so we hope to release it in November.

## Experiment

I set up an experimental site [here](https://yuhattor.github.io/innersourcecommons.org/ja/), and working at jp-translation branch on [my github repository](https://github.com/yuhattor/innersourcecommons.org/tree/jp-translation)

I've only translated the top page, so the rest will get 404.

image

## What I learned after experiment

As I worked on the translation, I noticed several things.

- There is an i18n settings folder, but it is not used
- `config.yaml` can be split into `config/_default/config.yaml`, `config/_default/languages.yaml` and etc. to make it easier to i18n things like menu notation.
- Since hugo is used, the md files are in a format that allows for easy translation to begin, and we can translate them in the same style as we have done with Learning Path. However, files like `layouts/shortcodes/about-text.html` have some English embedded in them. it would be easier to manage these parts of html by moving them out to i18n/en.yaml and so on.
- Right now, we have to go to the Learning Path page to get the language selection screen in the upper right corner. For supported languages, I would like to display the language selection on all pages
- *Optional: There are several relatively large png, jpg and pdf files in the repository. This is also causing the build time to be very long. It might be a good idea to compress image files into webp, etc. and manage pdfs in Object Storage, etc. Especially since pdfs are not updated often.

---
I would like to hear your opinions.
Especially about the structure of hugo and how to operate it.
I wonder why Learning Path is in different repositories, is there some background that prevents integration?

\+ sorry, the ```bug``` label is not applicable for this. Please change it...

### LINKED ISSUE #413: Fix broken links
The following links need to be modified

https://github.com/InnerSourceCommons/innersourcecommons.org/actions/runs/3566445109/jobs/5993320498

### Errors in content/en/learn/learning-path/product-owner/06.ja.md
* [https://innersourcecommons.org/ja/learn/learning-path/trusted-committer[Trusted](https://innersourcecommons.org/ja/learn/learning-path/trusted-committer[Trusted): Failed: Network error

### Errors in content/en/events/isc-fall-2018.md
* [https://www.safaribooksonline.com/learning-paths](https://www.safaribooksonline.com/learning-paths): Failed: Network error
* [https://mgmtacct.unca.edu/faces/mary-lynn-manns-phd](https://mgmtacct.unca.edu/faces/mary-lynn-manns-phd): Failed: Network error

### Errors in content/en/events/isc-fall-2017.md
* [http://openitp.org/](http://openitp.org/): Failed: Network error
* [http://www.flychicago.com/ohare/home/pages/default.aspx](http://www.flychicago.com/ohare/home/pages/default.aspx): Failed: Network error
* [http://www.flychicago.com/midway/home/pages/default.aspx](http://www.flychicago.com/midway/home/pages/default.aspx): Failed: Network error
* [http://www.napervilleparks.org/the-riverwalk](http://www.napervilleparks.org/the-riverwalk): Failed: Network error
* [http://newamerica.net/](http://newamerica.net/): Timeout
* [http://www3.hilton.com/en/hotels/illinois/hilton-lisle-naperville-NAPHIHF/index.html](http://www3.hilton.com/en/hotels/illinois/hilton-lisle-naperville-NAPHIHF/index.html): Failed: Network error

### Errors in content/en/events/isc-fall-2016.md
* [http://www.harpoonbrewery.com/breweries/boston/brewery-tours](http://www.harpoonbrewery.com/breweries/boston/brewery-tours): Failed: Network error

### PR DESCRIPTION
**Pull request by yuhattor**
# Changes
The following changes are made for i18n support.
Please check #355 for more details.

This PR will make significant changes to the structure, but the impact will be limited and will not affect the current English pages or the Learning Path international pages in any way. Users will not see any changes. This is just laying the foundation to make it easier to support i18n in the future.
Please click here to view the staging site.
https://www.innersourcecommons.jp/

**The main changes are as follows**

- Moved `contents/` to `contents/en`
- Split `config.yaml` into several files
- Add `i18n/en.md`. 
- Add `i18n.md` and edit `README.md`

## Upcoming i18n support implementations

1. i18n foundation [This PR]
  Due to the nature of Hugo's i18n support, the directories will be arranged as `contents/en`, `contents/ja`, and so on. If we send a PR to main after everything is in place, the changes will be too large.
	By moving existing files to `contents/en` in advance, we can run i18n support development activity and innersourcecommons.org management in parallel, with minimal impact on the operation of innersourcecommons.org.
	In this configuration, `content/en` is set as root instead of `content`, which creates a situation where the file `01.ja.md` temporarily exists in the `en` scope. The path of the program in this case is as follows
  `content/en/learn/learning-path/introduction/01.ja.md`.
  However, this does not affect the existing LearningPath URL paths, and future development will relocate these files to the correct locations.

2. InnerSource Learning Path's repository change
  There is almost nothing to change on the LearningPath side this time, except for one thing.
  LearningPath uses GitHub Actions to publish content to innersourcecommons.org.
  The following line needs to be changed. This configuration needs to be done as soon as possible after this PR is closed.
  https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/64160193c1cc1abf56e3dab352b26517a47e91e0/.github/workflows/publish-to-website.yml#L44

  ```git
  - cp -r newsite/. ... /... /innersourcecommons.org/content/learn/learning-path/
  + cp -r newsite/. ... /... /innersourcecommons.org/content/en/learn/learning-path/
  ```

3.  Add another language (Japanese will be the first)
  Japanese changes will be sent to May in PR after the basic part is done.
	At the same time, we will add a job to the LearningPath GitHub Actions to make the directory structure of LearningPath for each language consistent with that of InnerSourceCommons.org.
	The InnerSource Learning Path contains files for multiple locales per directory for a single topic. On the other hand, innersourcecommons.org will place contents separately from the top tier, such as content/en, content/en, content/ru.
	As in this case, these changes will be made simultaneously at innersourcecommons.org and LearningPath. However, we can manually place existing LearningPath contents in innersourcecommons.org beforehand, so users will not lose visibility of LearningPath content.

### CODE REVIEW

**Comment by yuhattor** [comment]
@voborgus @rrrutledge Could you please check this PR?
Also, this PR has a small dependency with this one.
https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/515

By the way, LinkCheck is failing, but succeeds in my environment below. I'm checking this one now too.
https://github.com/isc-i18n/innersourcecommons.org/actions/runs/3564996421

**Comment by yuhattor** [comment]
Apparently, this LinkCheck is only applied to files that have been modified, and files that have not been checked before but have broken links are now in error.

```
 md_files=`find ${{ steps.changed-files.outputs.all_changed_files }} -maxdepth 0 -name "*.md" | tr '\n' ' '`
          echo "MARKDOWN_FILES=$md_files" >> $GITHUB_ENV
```

The following link seems to apply, should I fix it on this PR?

### Errors in content/en/learn/learning-path/product-owner/06.ja.md
* [https://innersourcecommons.org/ja/learn/learning-path/trusted-committer[Trusted](https://innersourcecommons.org/ja/learn/learning-path/trusted-committer[Trusted): Failed: Network error

### Errors in content/en/events/isc-fall-2018.md
* [https://www.safaribooksonline.com/learning-paths](https://www.safaribooksonline.com/learning-paths): Failed: Network error
* [https://mgmtacct.unca.edu/faces/mary-lynn-manns-phd](https://mgmtacct.unca.edu/faces/mary-lynn-manns-phd): Failed: Network error

### Errors in content/en/events/isc-fall-2017.md
* [http://openitp.org/](http://openitp.org/): Failed: Network error
* [http://www.flychicago.com/ohare/home/pages/default.aspx](http://www.flychicago.com/ohare/home/pages/default.aspx): Failed: Network error
* [http://www.flychicago.com/midway/home/pages/default.aspx](http://www.flychicago.com/midway/home/pages/default.aspx): Failed: Network error
* [http://www.napervilleparks.org/the-riverwalk](http://www.napervilleparks.org/the-riverwalk): Failed: Network error
* [http://newamerica.net/](http://newamerica.net/): Timeout
* [http://www3.hilton.com/en/hotels/illinois/hilton-lisle-naperville-NAPHIHF/index.html](http://www3.hilton.com/en/hotels/illinois/hilton-lisle-naperville-NAPHIHF/index.html): Failed: Network error

### Errors in content/en/events/isc-fall-2016.md
* [http://www.harpoonbrewery.com/breweries/boston/brewery-tours](http://www.harpoonbrewery.com/breweries/boston/brewery-tours): Failed: Network error

**Comment by yuhattor** [comment]
After checking each of these, this does not appear to be a LinkCheck error. LinkCheck is working correctly because the content itself is missing. Perhaps this is the content that needs to be rewritten. I thought this was not something that should be done in this PR, so I have raised another Issue in #413 :)

**Review by voborgus — APPROVED** [review]
Awesome! 
Just checked locally – everything goes well. Thank you for such massive contribution. Ready to merge that when needed.

**Comment by yuhattor** [comment]
@voborgus could you check if the conflict was successfully resolved?

**Comment by yuhattor** [comment]
@voborgus could you check the conflict was successfuly resolved1

**Pull request merged**
