### PR TITLE
Adding State of InnerSource 2021 survey

### PR DESCRIPTION
**Pull request by clcoffey**
I created a new page with a call to action to complete the State of InnerSource Survey. 

We still need to change the button text instead of Read Research to say Take Survey.

### CODE REVIEW

**Comment by clcoffey** [comment]
@spier do you think you might be able to help with this?

**Comment by spier** [comment]
@clcoffey besides a review of this PR, do you need anything else?

**Comment by clcoffey** [comment]
Hi @spier, yes, I am trying to change the text on this button alone to Take Survey rather than Read Research. I thought you might be able to help because I know you put together the Research pages. :-)

**Comment by spier** [comment]
Got it. Let me check ...

**Comment by spier** [comment]
@clcoffey I think I made the change that you were looking.

I also made a couple of other smaller changes in the Research section.
Please check out the changes to see if you like them.

**Review by voborgus — APPROVED** [review]
Looks good to me

**Comment by clcoffey** [comment]
Thanks for all your help @spier!

**Pull request merged**
