### PR TITLE
Publish announcement of the 2023 Board

### PR DESCRIPTION
**Pull request by direnakkoc**
The issue applied:

- https://github.com/InnerSourceCommons/innersourcecommons.org/issues/544

### CODE REVIEW

**Review by spier — COMMENTED** [review]
Thank you for this work!

The changes to the board page might collide with other changes to the page in #545?
Might be best to get that other PR merged first, and to undo the changes to the `board/_index.md` page here.

Also I noticed that the headshot pictures are not evenly aligned in the image, and possibly have different sizes. I think I found the original source of that image, so I will try to fix that.

**Comment by direnakkoc** [comment]
Thanks @spier!
Please, let me know if there is something that I can do.

**Comment by spier** [comment]
@direnakkoc I fixed the alignment of the headshots in the image. While at it, I also reduced the image file sizes of other images in the same folder.

Further I found that we had a bug with the announcements:
If there is more than one announcement with the flag `featured: true`, then only the newest one will be shown, while all other ones will be hidden. I removed that flag from all previous announcement, which fixes the issues for now.

Maybe we can find a more stable way to fix this. Any ideas @voborgus?

**Comment by spier** [comment]
@direnakkoc what do you think about removing the changes to `board/_index.md` from this branch/PR?

**Review by spier — APPROVED** [review]
Other than the last comment I left, this looks good to me.

**Pull request merged**
