### PR TITLE
New Announcements Page

### PR DESCRIPTION
**Pull request by clcoffey**
I created a new Announcements page as per https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/111

A few things that we still need to do:
- List the announcements on the Announcements page
- Make sure the header image appears in each announcement article
- Write the content for the Sponsorship announcement
- Add the links in the menus under About Us.

### CODE REVIEW

**Comment by clcoffey** [comment]
@voborgus could you help with the first two items in the list above? 
@claredillon the article for sponsorship is created all you have to do is add the text. I already included the image in the header.
@claredillon what place should Announcements take in the About Us menu?

**Comment by voborgus** [comment]
image

Changed layout

**Comment by claredillon** [comment]
This looks so nice - thanks @clcoffey and @voborgus . I have checked the announcement text - and looks good (made a small formatting change to board announcement).

**Comment by claredillon** [comment]
Quick additional question @voborgus - would it be possible to have the secondary list ordered in reverse order timeline? i.e. FINOS (most recent) on the left?

**Comment by voborgus** [comment]
@claredillon yeah just fixed this

**Review by voborgus — APPROVED** [review]
thanks for the PR!

**Comment by voborgus** [comment]
should we merge this right now?

**Pull request merged**
