### PR TITLE
Changes order for the board members and governance page

### LINKED ISSUE #748: Move People to Past Directors and Officers on Board & Governance Page
Hi @andrea-kyurchiev 

Please move Isabel Drost-Fromm, Russell Rutledge and Dmitrii Sugrobov to the 'Past Directors and Officers' section. 

When you move them, you can delete any titles associated with their current role (e.g. delete 'Chair' for Isabel). 

In the Past Directors and Officers' section, Please move:

- Isabel between Danese Cooper and Jacob Green
- Russell Rutledge underneath Klaas-Jan Stol
- Dmitrii between Russell Rutledge and Johannes Tigges

### PR DESCRIPTION
**Pull request by andrea-kyurchiev**
Closes #748

### CODE REVIEW

**Review by CiaraFlanagan — COMMENTED** [review]
Looks great @andrea-kyurchiev 

I'll approve and merge this closer to our announcement.

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan moving Russ down makes the Elected Officers section empty: 
image
Should that section be hidden?

**Comment by CiaraFlanagan** [comment]
> @CiaraFlanagan moving Russ down makes the Elected Officers section empty: image Should that section be hidden?

Yes - that would be great, @andrea-kyurchiev

**Review by CiaraFlanagan — APPROVED** [review]

**Review by kschueths — APPROVED** [review]
Looks good

**Review by mcobby — CHANGES_REQUESTED** [review]
Requesting update to my bio. Matt’s mission for most of his career has been to improve the daily lives of software engineering teams, wrangling people & technology through engineering evolutions.  He is a veteran of Developer Experience over the past 8 years and believes that InnerSource is a key factor in building a good Developer Experience and has run a large scale InnerSource program for a bank.  He is currently CTO for CXGuardian.ai, building a platform to help companies & engineers adopt AI with fair & ethical governance to reshape their business and productivity. 

Previously a Director of Engineering for Deloitte, he consulted with Technology Executives on engineer strategy and has also worked with RWE Supply & Trading, BP, Shell and National Australia Bank.  With over 18 years transformation experience in the UK, Europe & Australia, he has a passion for mentoring engineers towards engineering excellence and is an active supporter of technical & local communities.

**Comment by andrea-kyurchiev** [comment]
@mcobby this should be it
image

**Comment by CiaraFlanagan** [comment]
Hi @mcobby 

Just to assure you, we're updating all the Board members' bios, photos and their order on the page in the next Pull Request.  This one is just to move previous members onto the correct section of the page and help us chunk the work.

**Comment by CiaraFlanagan** [comment]
@mcobby 

We're very happy to add your proposed changes now by the way (we just need to get it approved and merged).

**Comment by CiaraFlanagan** [comment]
> Looks good

Thanks very much @kschueths

**Review by mcobby — APPROVED** [review]

**Pull request merged**
