### PR TITLE
Edit the bios order on the Board page

### PR DESCRIPTION
**Pull request by direnakkoc**
The issue applied:

- https://github.com/InnerSourceCommons/innersourcecommons.org/issues/543

### CODE REVIEW

**Comment by spier** [comment]
Technically Silona and Max are not board members, even though they are sharing the treasurer role.

With this change it will look like we have 11 rather than 9 board members. Is this what we want?

**Comment by CiaraOSPO** [comment]
> Technically Silona and Max are not board members, even though they are sharing the treasurer role.
> 
> With this change it will look like we have 11 rather than 9 board members. Is this what we want?

Let me get back to you on this @spier

**Comment by claredillon** [comment]
THere is confusion because sme officers are not board members, but some board members are officers. Recommend the following headings:
- Board of Directors - listing all board members, with those who are also officers topping the list, and other listed alphabetically.
- Elected Officers - listing Silona and Max
- Past Board Members and Officers : whoever acted as either director or officer in the past, not in above two categories. 
- 
- Perhaps in the future, this last section could be arranged by term, with explicit info on the roles people played. This would be very handy from a governance perspective, as we sometimes have to report who was on the board or in a role in a particular time period. It would also add to the history of the organization.

**Comment by tsadler1988** [comment]
> Perhaps in the future, this last section could be arranged by term, with explicit info on the roles people played. This would be very handy from a governance perspective, as we sometimes have to report who was on the board or in a role in a particular time period. It would also add to the history of the organization.

We do keep a record of this as part of the annual election process. It might be OK to share this publicly but for now I'll just share it with the board + @claredillon.

**Comment by CiaraOSPO** [comment]
Hi @claredillon

Following your comment, I'm double checking that I have the updated list of Board Members and Elected Officers in the correct order:

The Current Board
Matt Cobby
Georg Grütter
Yuki Hattori
Dmitrii Sugrobov
Isabel Drost-Fromm (Chair)
Daniel Izquierdo Cortazar (President)
Russell Rutledge (Vice-President)
Tom Sadler (Secretary)
Sebastian Spier (Assistant Secretary)

Elected Officers
Silona Bonewald (Treasurer)
Max Capraro (Assistant Treasurer)

Silona's and Max's details will be removed from 'History' section.

**Comment by claredillon** [comment]
We usually list the Board members who are officers first (as with current page). So:

**The Current Board of Directors**
Here are our current board of directors, including the official roles they have been elected to fulfill. 

Isabel Drost-Fromm
Chair

Daniel Izquierdo Cortazar
President

Russell Rutledge
Vice President


Tom Sadler
Secretary


Sebastian Spier
Assistant Secretary


Matt Cobby
Georg Grütter
Yuki Hattori
Dmitrii Sugrobov

**Elected Officers**
The following elected officers do not sit on the board of directors. 

Silona Bonewald
Treasurer

Maximilian Capraro
Assistant Treasurer

**Past Directors and Officers**
These fine people have served on our Board in previous years and we are listing them here to show our gratitude for their work. Thank you for your dedication to InnerSource and your active support of the InnerSource Commons Foundation!

... and include all the others who are not included above

**Comment by CiaraFlanagan** [comment]
Thanks for clarifying @claredillon

**Comment by CiaraFlanagan** [comment]
Hi @direnakkoc 

We've had some clarification now on this Board Page and need the following changes:

1. Please change the title: 'The current Board' to 'The Board of Directors'

2. Add this text below the title:  
Here is our current Board of Directors, including the official roles they have been elected to fulfill.

3. The order of the Bios under 'The current Board of Directors' should be changed to the following order:

Isabel Drost-Fromm
Daniel Izquierdo Cortazar
Russell Rutledge
Tom Sadler
Sebastian Spier
Matt Cobby
Georg Grütter
Yuki Hattori
Dmitrii Sugrobov

4. Underneath the 'The Current Board of Directors' and the bios, we need a new section with the Title 'Elected Officers'.

5. Add this text below the title:  The following elected Officers do not sit on the Board of Directors.

6. The following bios should be moved under 'Elected Officers' and should be listed in the following order:

Silona Bonewald
Maximilian Capraro

7. Change title 'History:' to 'Past Directors and Officers'

8. The list of people under the 'Past Directors and Officers' heading should be in the following order:

Danese Cooper
Jacob Green
Klaas-Jan Stol
Johannes Tigges
Cedric Williams
Tim Yao

Thank you!

**Comment by spier** [comment]
I made one change to the highlighting color. 
Other than that this looks great. Thanks a lot @direnakkoc!

**Review by spier — APPROVED** [review]

**Comment by CiaraFlanagan** [comment]
Hi there @spier 

Just noting that the merge doesn't seem to have been updated on the webpage ...

Any thoughts on this?

**Comment by spier** [comment]
This PR has not been merged yet. Maybe you are confusing it  with #546?

**Comment by CiaraFlanagan** [comment]
Thanks for clarifying @spier!

**Pull request merged**
