### PR TITLE
Japanese page update

### LINKED ISSUE #564: 🇯🇵 Japanese: Content Consistency Issue
# i18n Contents Consistency Issue

The following files may have consistency issues with the English version. Please check and update the files.

This issue is created when there is an update to content/en. It compares the git update history to let you know what updates are overdue. The issue should be closed when the update is complete.
<details><summary><b>"InnerSource Commons"</b> (content/en/_index.md)</summary>

- Original File(en): [content/en/_index.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/en/_index.md)
- Translated File(ja): [content/ja/_index.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/ja/_index.md)
- [Diff on GitHub](https://github.com/yuhattor/innersourcecommons.org/compare/...54612b6756f8c9d17a15ba233ab6675d14a1e3ad)
- Days since overdue updates: 158 days
```diff
# diff --git a/content/en/_index.md b/content/en/_index.md
# index 96769bd3f..a27bf0daf 100644
# --- a/content/en/_index.md
# +++ b/content/en/_index.md
@@ -98,7 +98,7 @@ title: "InnerSource Commons"
       </div>
       <div class="col-md-5 offset-md-1">
         <p class="h2 section-title">Stay Connected</p>
-        <p class="mb-4">Most of the action in the community happens on our <a href="https://join.slack.com/t/innersourcecommons/shared_invite/zt-1l4a602b6-DKD0B0Y8~WE4aDf~o1xCRw">Slack Channel</a>. You can also keep informed about the InnerSource Commons news, events and activities by signing up to our mailing list below, follow us on <a href="https://twitter.com/InnerSourceOrg">Twitter</a> and <a href="https://www.linkedin.com/company/innersourcecommons">LinkedIn</a>, and subscribing to our <a href="https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA">YouTube Channel</a>.</p>
+        <p class="mb-4">Most of the action in the community happens on our <a href="https://join.slack.com/t/innersourcecommons/shared_invite/zt-1msf8vcqu-fYEHcyI1l4eSPq6rGprMXA">Slack Channel</a>. You can also keep informed about the InnerSource Commons news, events and activities by signing up to our mailing list below, follow us on <a href="https://twitter.com/InnerSourceOrg">Twitter</a> and <a href="https://www.linkedin.com/company/innersourcecommons">LinkedIn</a>, and subscribing to our <a href="https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA">YouTube Channel</a>.</p>
         <p class="h3 section-title">Sign up to our mailing list</p>
         {{< contact-form >}}
       </div>
```
</details>

<details><summary><b>"Members"</b> (content/en/about/members.md)</summary>

- Original File(en): [content/en/about/members.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/en/about/members.md)
- Translated File(ja): [content/ja/about/members.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/ja/about/members.md)
- [Diff on GitHub](https://github.com/yuhattor/innersourcecommons.org/compare/...ef36cebe086842d2a2e6fee087c8ea8182d5f7d9)
- Days since overdue updates: 11 days
```diff
# diff --git a/content/en/about/members.md b/content/en/about/members.md
# index 59cdf9697..a4e86d3ec 100644
# --- a/content/en/about/members.md
# +++ b/content/en/about/members.md
@@ -15,6 +15,7 @@ Membership is purely merit-based, free of any cost, and restricted to individual
 ## Members of the InnerSource Commons Foundation
 
 * Ada Dai
+* Bill Higgins
 * Cedric Williams
 * Clare Dillon
 * Cristina Coffey
@@ -23,11 +24,13 @@ Membership is purely merit-based, free of any cost, and restricted to individual
 * Dmitrii Sugrobov
 * Fei Wan
 * Georg Gr&#x00FC;tter
+* Guilherme Dellagustin
 * Igor Zubaiurre 
 * Isabel Drost-Fromm
 * Jacob Green
 * Jerry Tan
 * Johannes Tigges
+* Katie Schueths
 * Klaas-Jan Stol
 * Matt Cobby
 * Maximilian Capraro
@@ -37,4 +40,5 @@ Membership is purely merit-based, free of any cost, and restricted to individual
 * Silona Bonewald
 * Tim Yao
 * Tom Sadler
+* Yuki Hattori
 * Zack Koppert
```
</details>

<details><summary><b>"Board & Governance"</b> (content/en/about/board/_index.md)</summary>

- Original File(en): [content/en/about/board/_index.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/en/about/board/_index.md)
- Translated File(ja): [content/ja/about/board/_index.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/ja/about/board/_index.md)
- [Diff on GitHub](https://github.com/yuhattor/innersourcecommons.org/compare/...b588f6a79aa30111d3ce49f49e498c14528e0802)
- Days since overdue updates: 11 days
```diff
# diff --git a/content/en/about/board/_index.md b/content/en/about/board/_index.md
# index 7e2d4bb23..195f0b390 100644
# --- a/content/en/about/board/_index.md
# +++ b/content/en/about/board/_index.md
@@ -120,16 +120,3 @@ All of Cedric’s work, personal and professional, has been guided by my desire
 {{< board-member name="Tim Yao" image="/images/about/Tim_Yao.jpeg" >}}
 Tim is a Distinguished Member of Technical Staff and the Product Manager for Nokia Continuous Delivery in Nokia Cloud and Network Services. Over his twenty-plus year career in telecommunications, Tim has held roles in innovation, software testing, system engineering, architecture, and procurement. He served six years on the Alcatel-Lucent FOSS Executive Committee. Tim has experience creating grass roots communities within the company and outside of it; he is a volunteer co-Municipal Liaison for National Novel Writing Month.
 {{< /board-member >}}
-
-
-
-
-
-
-
-
-
-
-
-
-
```
</details>

<details><summary><b>"InnerSource Stories"</b> (content/en/stories/_index.md)</summary>

- Original File(en): [content/en/stories/_index.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/en/stories/_index.md)
- Translated File(ja): [content/ja/stories/_index.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/ja/stories/_index.md)
- [Diff on GitHub](https://github.com/yuhattor/innersourcecommons.org/compare/...6607fed04042cfc954a52728a0df3e0b2e0de521)
- Days since overdue updates: 135 days
```diff
# diff --git a/content/en/stories/_index.md b/content/en/stories/_index.md
# index a4d0904e2..ca46779fa 100644
# --- a/content/en/stories/_index.md
# +++ b/content/en/stories/_index.md
@@ -44,6 +44,9 @@ aliases:
       {{< company name="BBC" image="/images/logos/bbc.png" video="https://www.youtube.com/watch?v=pEGMxe6xz-0" author_name="Steph Egan" author_title="Software Engineering Team Lead" >}}
       Our tools have been built been built from the ground up with an expectation of InnerSource … The way that we encourage that in a very disparate organization is mostly word of mouth and clear documentation.
       {{< /company >}}
+      {{< company name="BBVA AI Factory" image="/images/logos/BBVA_AI_factory.png" article="https://www.bbvaaifactory.com/mercury-acelerando-la-reutilizacion-en-ciencia-de-datos-dentro-de-bbva/" author_name="Rafael Hernandez Murcia" author_title="Senior Manager Data Scientist" >}}
+      Thanks to an InnerSource strategy we are scaling the reusability of Data Science code in a wide range of countries and business areas at BBVA. To achieve this, we developed a Python library, named Mercury.
+      {{< /company >}}
       {{< company name="BCG Gamma" image="/images/logos/bcg.png" article="https://github.com/customer-stories/bcg-gamma" >}}
       {{< /company >}}
       {{< company name="Bitergia" image="/images/logos/bitergia.png" article="https://www.linkedin.com/feed/update/urn:li:activity:6711604569262067712/?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A6711604569262067712%29" >}}
```
</details>

<details><summary><b>"InnerSource Services Directory"</b> (content/en/community/services.md)</summary>

- Original File(en): [content/en/community/services.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/en/community/services.md)
- Translated File(ja): [content/ja/community/services.md](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/ja/community/services.md)
- [Diff on GitHub](https://github.com/yuhattor/innersourcecommons.org/compare/...f884199985068b898d66131d44fefa9f59e4901a)
- Days since overdue updates: 25 days
```diff
# diff --cc content/en/community/services.md
# index c02605b38,ebff4599b..fd25ad25e
# --- a/content/en/community/services.md
# +++ b/content/en/community/services.md
@@@ -20,7 -20,7 +20,7 @@@ We do our best to ensure that the infor
          <td><img src="/images/logos/bayave.png" alt="Bayave"><img style="width: 30%;
    height: auto; display: block; margin-left: auto; margin-right: auto;"></td>
          <td>Training and Consulting Services</td>
--        <td class="title">Bayave provides training and consulting services on open source, InnerSource, and product strategy. You can learn more on our website <a href="https://bayave.com/"> https://bayave.com/ </a> or contact us by email at <a href="mailto:info@bayave.com"> info@bayave.com </a> directly.
++        <td class="title">Bayave provides training and consulting services on open source, InnerSource, and product strategy. You can learn more on our <a href="https://bayave.com/"> website </a> or contact us by email at <a href="mailto:info@bayave.com"> contact Bayave</a> directly.
          </td>
      </tr>
      <tr>
```
</details>

### PR DESCRIPTION
**Pull request by yuhattor**
## Update translation related items

Please review and approve this!

### Update translation consistency check GitHub Action

See the fixed implementation here
https://github.com/InnerSourceCommons/innersourcecommons.org/issues/564

### Updated translation

Updated Japan page to the latest
https://github.com/InnerSourceCommons/innersourcecommons.org/issues/564

- "InnerSource Commons" (content/en/_index.md)
- "Members" (content/en/about/members.md)
- "Board & Governance" (content/en/about/board/_index.md)
- "InnerSource Stories" (content/en/stories/_index.md)
- "InnerSource Services Directory" (content/en/community/services.md)

### CODE REVIEW

**Comment by yuhattor** [comment]
@bory_kb Could you please see and confirm if it's okay:)
Thanks!

**Comment by bory-kb** [comment]
LGTM!!

**Review by spier — APPROVED** [review]
If 2 members of the Japanese community are happy with the translation, then I am sure this is good to go live 👍

Thank you for making and keeping the site available for people that are more comfortable with Japanese than with English!

**Comment by yuhattor** [comment]
Thank you!!!!!

**Pull request merged**
