### PR TITLE
Learning path automation

### PR DESCRIPTION
**Pull request by tsadler1988**
Adds new GitHub action to re-generate Learning Path content once an hour.

Tested on my fork:
- https://github.com/tsadler1988/innersourcecommons.org/actions/workflows/learning-path.yml
- https://github.com/tsadler1988/innersourcecommons.org/commit/f894be132cf4f4cba2c9f25b424a8c1de62d30ed

Some things to consider:
- Not 100% sure this will work and we won't know until it is merged
  - There may be branch protection rules in place (admins should be able to answer this question)
  - [Scheduled cron jobs are not guaranteed to run](https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/), which is why I'm building more often than is really necessary (daily would probably be sufficient)
 - Ideally would be triggered by a push to Learning Path, but this has various difficulties
   - If this Action was run in the Learning Path repo, we would need to create an access token for it with write access to this repo
   - We might be able to trigger from Learning Path via a [manual event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events) but this may have the same issue re: access token

### CODE REVIEW

**Comment by voborgus** [comment]
Hi! Great job.
Seems something is broken in your fork:
image

Would it be so hard to change it to trigger by event rather than cron? If it will be helpful, I can create an access token for this repo, it's can be done just with several clicks.
Random pushes by cron to production are very dangerous and can break the website anytime and suddenly.
I was wondering about:
* Trigger of action in the LP repository by commit to their master branch (all is happening out of this repo)
* LP action generates pages and sends commit to the website repo to some separated branch
* PR is opened automatically or manually at the first stages and checked by hands and merged to master of the website.

What do you think @tsadler1988?

**Comment by tsadler1988** [comment]
> Scheduled cron jobs are not guaranteed to run, which is why I'm building more often than is really necessary (daily would probably be sufficient)

[Testing overnight on my fork](https://github.com/tsadler1988/innersourcecommons.org/actions/workflows/learning-path.yml) showed that I did get a build every hour, but up to 40 minutes later than scheduled, so I think this is probably OK.

> Seems something is broken in your fork

This is sort of expected; it's because there haven't been any changes to Learning Path:
```
Run git add .
On branch temp-main
Your branch is up to date with 'origin/temp-main'.

nothing to commit, working tree clean
Error: Process completed with exit code 1.
``` 

But I can make the git commands exit gracefully instead of throwing an error. Although, this won't be necessary if we change from scheduled to triggered.

> I can create an access token for this repo, it's can be done just with several clicks.

I don't think it's quite that simple I'm afraid. If you create a Personal Access Token with push access, it will have push access to _everything_ you do - you can't scope it to an individual repo. I would instead recommend creating a new GitHub account purely for this purpose, rather than opening up a potential security hole on any other repos you have push access on.

I have an idea to trigger this workflow from Learning Path without a token, so I will try that first. But if not, then creating a bot account would be helpful!

Another alternative would be to create a GitHub app for this, but that would take a fair amount of additional work and investigation - let's call that Plan C 😄 .

> PR is opened automatically or manually at the first stages and checked by hands and merged to master of the website.

Happy to do this, but it would be nice to gain enough confidence to make this fully automated in the future (e.g. run the `github pages` action to ensure nothing breaks).

**Comment by voborgus** [comment]
> I don't think it's quite that simple I'm afraid. 

As far as I know, this section will allow us to open the access only for this repo:

image

So the items to do:
* Generate new private and open SSH key 
* Put public part in this repository as deploy key with write access
* Put secret part to LP secrets and use it when working with website repo.

**Comment by lenucksi** [comment]
Awesome, thanks for creating this! :rocket: 
I've had success with the bot approach and agree to the possible problems around personal tokens. I don't know about any protected master setups so far.

**Comment by tsadler1988** [comment]
Ahh Deploy Keys look like just what we need! For some reason, all the examples I could find used PATs.

Yes please @voborgus, if you can create a deploy key and add it as a secret to the Learning Path I'll see what I can do. I can do this myself on my forks to investigate.

**Comment by voborgus** [comment]
Done, public part in this repo with write access, private part in the Slack's DM (I have no admin access in the LP repo)

**Comment by rrrutledge** [comment]
Looks like great collaboration on this so far.  Really excited to see where this goes.

**Comment by tsadler1988** [comment]
Updated this PR to simply raise a PR on the expected branch where Learning Path updates will be pushed to (this is done via https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/432).

This is necessary because there is no way to raise a PR via a GitHub Deploy token (they are SSH only, and the GitHub API does not support access via SSH).

**Review by voborgus — APPROVED** [review]
thanks for the clean and wonderful work. happy to merge

**Pull request merged**
