### PR TITLE
Terse notes for the meeting on 2021-06-23

### PR DESCRIPTION
**Pull request by lenucksi**
Please review and merge accordingly.

### CODE REVIEW

**Review by rrrutledge — APPROVED** [review]
Do you want to try putting in the count of approvals for each report?

**Comment by lenucksi** [comment]
> Do you want to try putting in the count of approvals for each report?

Sounds good, I'll do that in the next days!

**Review by gruetter — APPROVED** [review]

**Comment by voborgus** [comment]
can we merge this? @lenucksi

**Comment by rrrutledge** [comment]
> can we merge this? @lenucksi

Yes, I think that we can merge.  @lenucksi and I talked about putting approval counts in the board reports themselves.

**Pull request merged**
