### PR TITLE
[WIP] Thai Language Support 🇹🇭

### PR DESCRIPTION
**Pull request by yuhattor**
# Thai Language Support

The InnerSource Commons (ISC) website is available in multiple languages. We appreciate your help in translating the site to make it accessible to Thai speakers.

please keep in mind followings

Please note the following guidelines:

- Before beginning your translation, please read the i18n.md file for information on tools and processes.
- Do not edit or create any files under `content/en/learn/learning-path/`. These files are sourced from another repository and are not stored in the innersourcecommons.org repository. If you want to add or edit a language, please do so in the learning-path repository.
- Please do not include any untranslated files in your pull request (PR). Missing files will be automatically added from `content/en` at build time.

## Files to be translated

The following is a list of files that should be translated first. It is a good idea to translate from here, but you are not required to follow it.

**Setting files**

- [ ] i18n/th.yaml
- [ ] config/_default/menus.th.yaml

**Content files**

- [ ] content/th/about/announcements/_index.md
- [ ] content/th/about/_index.md
- [ ] content/th/about/sponsors.md
- [ ] content/th/about/members.md
- [ ] content/th/about/board/_index.md
- [ ] content/th/about/codeofconduct.md
- [ ] content/th/about/contact.md
- [ ] content/th/community/_index.md
- [ ] content/th/community/services.md
- [ ] content/th/events/_index.md
- [ ] content/th/_index.md
- [ ] content/th/learn/_index.md
- [ ] content/th/learn/books/managing-innersource-projects.md
- [ ] content/th/learn/books/innersource-patterns.md
- [ ] content/th/learn/books/_index.md
- [ ] content/th/learn/books/adopting-innersource-principles-and-case-studies.md
- [ ] content/th/learn/books/understanding-the-innersource-checklist.md
- [ ] content/th/learn/books/getting-started-with-innersource.md
- [ ] content/th/learn/patterns.md
- [ ] content/th/learn/research/state-of-innersource-survey-2021.md
- [ ] content/th/learn/research/state-of-innersource-survey-2016.md
- [ ] content/th/learn/research/_index.md
- [ ] content/th/learn/research/state-of-innersource-survey-2020.md
- [ ] content/th/redirects/patterns.md
- [ ] content/th/stories/_index.md
- [ ] content/th/stories/microsoft.md

### The conditions for merging are as follows

- [ ] Website-mainterners Approval
- [ ] Native check
	While machine translation can be useful for large volumes of text and can serve as a starting point for translation, it can also produce unprofessional results. In addition, since machine translation can be used by anyone with a browser extension, this translation project requires a more professional level
- [ ] At least 50% of the files in the "Files to be translated" section should be translated

### CODE REVIEW

**Comment by lenucksi** [comment]
Unrelated comment but the description is amazingly concise and to the point. Do we have that as a template for other use cases somewhere? Thanks @yuhattor and of course a big thank you to all the people participating in the translations and reviews!

**Comment by yuhattor** [comment]
@lenucksi This is just my messy summary empowered by ChatGPT. Lately I have been getting a lot of help from ChatGPT, no joke. I have most of the content in mind, but I have had ChatGPT help me with final formatting, structuring, and summarizing the main points. ChatGPT has its limitations and we can never get them to do it all, but they often help us to scale!

**Comment by lenucksi** [comment]
> @lenucksi This is just my messy summary empowered by ChatGPT. Lately I have been getting a lot of help from ChatGPT, no joke. I have most of the content in mind, but I have had ChatGPT help me with final formatting, structuring, and summarizing the main points. ChatGPT has its limitations and we can never get them to do it all, but they often help us to scale!

Thanks for the reply. Impressive work by ChatGPT then. I expected more messy output with far less structure from this AI. More like the Amazon referral spam blogs that are popular on certain sales topics (at least here #best10gizmosclickallouramazonreferrallinks).

**Comment by yuhattor** [comment]
Just a heads up, this is a tutorial video:)

[Contribute to innersourcecommons.org in Your Language](https://www.youtube.com/watch?v=gWXUgYIpJqg)

**Comment by mishari** [comment]
@yuhattor working on this branch at https://github.com/mishari/innersourcecommons.org/tree/i18n-th

**Comment by mishari** [comment]
@yuhattor is there a suggested priority list of files to be translated? Perhaps something like getting-started-with-innersource.md is the place to start

**Comment by yuhattor** [comment]
@mishari 
There is no priority, but getting-started-with-innersource.md may have the lowest priority.

getting-started-with-innersource.md is a description of the InnerSource book, not InnerSource itself. Also, the book Getting Started with InnerSource is licensed by O'Reilly Media and requires permission for translation. (Actually, the book itself is not licensed under a CC-BY license, so translations into other languages require permission. This statement that the book is CC-BY and can be edited is **incorrect**).
Also, since this is a translation of a book, it will take more work than translating pages and will need to be checked. This is a time-consuming process and needs to be done separately from the innersourcecommons.org translation.

Since the book is available in English, the people who will read it are English speakers. If someone who is not fluent in English gets to the getting-started-with-innersource.md page, it will not make much sense even if they can read getting-started-with-innersource.md, because they will not be able to read the book itself.

**Pull request closed without merging**
