### PR TITLE
Update by-laws

### PR DESCRIPTION
**Pull request by tsadler1988**
Created by copying the [February 2020 by-laws Google Doc with @rrrutledge's suggestions](https://docs.google.com/document/d/109XWFL_MypH9V2gMd8my0YFzxOQkwJTF/edit) into a [new Google Doc for November 2022](https://docs.google.com/document/d/1KJgq-zDad6Z0ZWpOzk8XFocl-zj_v4Uyq4TCEddysHg/edit), accepting the suggestions and printing to PDF.

Diff of PDFs attached created with [pdf-diff](https://pypi.org/project/pdf-diff/) (some spurious changes but content appears correct to me).

diff

### CODE REVIEW

**Review by rrrutledge — APPROVED** [review]
Thank you for doing this, @tsadler1988 ❗

**Comment by spier** [comment]
@tsadler1988 to clarify what you are asking the reviewer to check here:

a) Should the reviewer confirm that the new PDF gets displayed correctly on the website?
b) Do they also have to confirm that the bylaw change is the desired one?

If we could limit it to (a) then that would make this a lot faster.
Also thinking more about it (b) might actually be hard to do, as they might not have access to all information required to that.

The more I writing here, the more sure I am that you likely just wanted (a). Also @rrrutledge already approved this, and he wrote the text changes to the bylaw I believe, so we can assume the approval for (b) to be there.

I convinced myself enough now :)

While I am not part of the @InnerSourceCommons/website-maintainers team, I will still go ahead and merge this, as it seems important to get this live.

**Review by spier — APPROVED** [review]

**Comment by spier** [comment]
New bylaws are live:
https://innersourcecommons.org/documents/bylaws.pdf

Btw we have a mix of spellings.
`bylaws` - link, url
`by-laws` - in the doc itself

Looks like both spellings are correct though (at least in the dictionary where I checked).

So we can leave this as is, I guess?

**Review by clcoffey — COMMENTED** [review]
Thanks for updating this!

**Comment by rrrutledge** [comment]
Thank you for this review and merge, @spier ❗

**Comment by tsadler1988** [comment]
Thanks for the review and merge!

**Pull request merged**
