### PR TITLE
Add surveys under /learn/research

### PR DESCRIPTION
**Pull request by spier**
This implements the first part of #77.

- Adding new page /learn/research/ to host the State of InnerSource surveys.
- Change grid layout of /learn page to make thinks look more even with a list of 5 elements.

This page cab later on also host other research material.

### CODE REVIEW

**Comment by clcoffey** [comment]
Hi Sebastian, thanks for putting this together!  It looks good. I just have a couple of small suggestions.

Is there any chance we can use the first slide as a picture for the 2016 survey too? As it is currently formatted I think the 2016 survey is getting lost on the page.

Also, I think we need to ask for permission to use the author's emails directly on the page. Maybe it is best to remove the contact information for the moment.

**Comment by spier** [comment]
> Hi Sebastian, thanks for putting this together! It looks good. I just have a couple of small suggestions.
> 
> Is there any chance we can use the first slide as a picture for the 2016 survey too? As it is currently formatted I think the 2016 survey is getting lost on the page.

Instead of adding another picture of the 2016 survey, what do you think about using a general picture for "research"?
That might be better as we eventually want to add research articles to this page anyways. So having a picture that symbolizes not just the surveys but also research articles would be helpful then.

I added a sample image that I could find quickly but if you got an idea for a better image, let me know.

> Also, I think we need to ask for permission to use the author's emails directly on the page. Maybe it is best to remove the contact information for the moment.

I have removed the contact info. However the email addresses are already part of the PDF reports, so I suspect using them would be fine. Anyways you are probably right, let's err on the side of caution.

**Review by clcoffey — APPROVED** [review]
Looks great! Thanks @spier!

**Comment by spier** [comment]
Great, thanks. 

I have removed the now unused `surveys.jpg` on master directly:
https://github.com/InnerSourceCommons/innersourcecommons.org/commit/97efd4f7a72f99ee6a3a08b5ef93cce7f81f8eae

**Pull request merged**
