### PR TITLE
Creating a Sponsors page

### LINKED ISSUE #97: Sponsors page on Website
Create new sponsors page on the Website to show off the Partners and Supporters of InnerSource Commons.

### PR DESCRIPTION
**Pull request by clcoffey**
Closes https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/97

### CODE REVIEW

**Comment by clcoffey** [comment]
Not to be merged until next week after Go-Ahead is received from Clare.

**Review by claredillon — CHANGES_REQUESTED** [review]
Can we change the subtitle to the following text please (note email change):

"The InnerSource Commons Foundation is supported by our generous sponsors. There are two types of sponsors: our **Supporters** are organizations who want to support the ISC community and accelerate their internal InnerSource journey and our **Partners** are organizations who want to take a step further in helping to lead the InnerSource movement in the world, supporting ISC activities and mission.

We are thankful to all our sponsors for their support which contributes to growing our community and spreading the word about InnerSource. If you are interested in sponsoring InnerSource Commons and want to know more about our sponsorship programme please contact us at sponsor@innersourcecommons.org."



"

**Comment by clcoffey** [comment]
@claredillon Done

**Comment by voborgus** [comment]
feel free to make this draft mergeable using "ready for review" button since it will be ready :)

**Comment by clcoffey** [comment]
Thanks Dmitrii!

**Comment by clcoffey** [comment]
@claredillon I added Bitergia's logo to the partner list so this is ready to publish when you are ready. Screenshot below to see how it will look like :-) 
Our Sponsors page

**Review by claredillon — APPROVED** [review]

**Comment by voborgus** [comment]
great work! awesome @clcoffey @claredillon

**Pull request merged**
