### PR TITLE
replacing Summit event page

### PR DESCRIPTION
**Pull request by OliveCannon**
Replacing the summit event page with a different size

### CODE REVIEW

**Comment by spier** [comment]
@OliveCannon should we also delete `/images/events/Summit2022.png`?

**Review by clcoffey — DISMISSED** [review]
Hi Olive, can you rename this image to isc-2022.md instead of meetup-2022-10-16 We'd like to keep summit images separate to the meet-up images :-)

**Comment by OliveCannon** [comment]
Hi Cristina, 
I have renamed the file isc-2022

**Review by yuhattor — APPROVED** [review]
looks good!

**Review by yuhattor — APPROVED** [review]

**Review by yuhattor — APPROVED** [review]

**Comment by yuhattor** [comment]
@clcoffey
Can you approve this??

**Pull request merged**
