### PR TITLE
Adding march 9th event

### PR DESCRIPTION
**Pull request by OliveCannon**
Hi Yuki, 
can you push through this pull request please?
thanks, 
Olive

### CODE REVIEW

**Comment by yuhattor** [comment]
@OliveCannon 
It looks like a lot of the images have been deleted.
If you don't mind, can you make an updated version of just the content of the session?
https://github.com/InnerSourceCommons/innersourcecommons.org/pull/489/files

**Comment by yuhattor** [comment]
@OliveCannon 
I'm just wondering about this, was this intended?
image

Same as https://github.com/InnerSourceCommons/innersourcecommons.org/pull/486

**Comment by OliveCannon** [comment]
Hi Yuki, 

this was not intended!  Can you ensure it doesn't change as I made a mistake.  i'm not sure what I did as I only intended to add the March 9th event to the events page.  Would it be possible to close this PR and not implement any changes from it and I will redo the PR as a new one where I only specifically add the March 9th event?

thanks so much for catching this!
Olive

**Comment by yuhattor** [comment]
close this due to https://github.com/InnerSourceCommons/innersourcecommons.org/pull/491

**Pull request closed without merging**
