### PR TITLE
update event page with August call

### PR DESCRIPTION
**Pull request by OliveCannon**
Updating event page with August 16th event

### CODE REVIEW

**Review by clcoffey — CHANGES_REQUESTED** [review]
Hi Olive, 

The date should be 2022-08-16 and not 2022-07-13 (this is the date of the event)
image

The way it is now it shows up on the website in the past, after the July event.
image

**Comment by OliveCannon** [comment]
> Hi Olive,
> 
> The date should be 2022-08-16 and not 2022-07-13 (this is the date of the event) image
> 
> The way it is now it shows up on the website in the past, after the July event. image

**Comment by OliveCannon** [comment]
HI Cristina, I've changed that now.  Thanks

**Review by clcoffey — APPROVED** [review]

**Comment by clcoffey** [comment]
Thanks Olive!

**Pull request merged**
