### PR TITLE
adding Jan 10th event to ISC site

### PR DESCRIPTION
**Pull request by OliveCannon**
adding Jan 10th event to ISC site

### CODE REVIEW

**Review by clcoffey — APPROVED** [review]
Looks good to me Olive. Thanks!

**Comment by spier** [comment]
@clcoffey in your workflow, who is meant to do the merging here? 
You (the reviewer) or Olive (the author of the PR). 
Both approaches have their merits, so it is just a matter of choosing the approach you like :)

**Comment by clcoffey** [comment]
I used to do it but I am trying to get people to do it themselves so they get full credit. :-)

**Comment by spier** [comment]
> I used to do it but I am trying to get people to do it themselves so they get full credit. :-)

@clcoffey if you you mean credit as in "green dots on their [GitHub contributor chart](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/viewing-contributions-on-your-profile#activity-overview)", that can also be achieved using the "squash and merge" feature in the GitHub UI.

Also not everybody opening a PR might be able to even merge it themselves. Depends on the repo settings i think.

As I am not 100% sure about the "squash and merge" bit, I will try this out now on this PR itself. Hope that is ok :)

**Comment by spier** [comment]
When using the squash+merge, GitHub shows the relevant info in the UI already.
While I would be the one here doing the merging, the commit and authorship/credit would be attributed to Olive.

Screenshot 2022-12-12 at 09 22 28

**Comment by spier** [comment]
@clcoffey as final proof of my theory, here the last two PRs that I merged:

The top one being a squash+merge, hence correctly attributed to Olive.
The bottom one being a merge commit, where all commits got attributed to me.

So I think squash+merge might be the way to go, in terms of correct credits/attribution.

Screenshot 2022-12-12 at 13 04 22

_Note:_

There are other situations where other merge approaches are more helpful.
They all have there place i.e. it is not that one is per see "better" than the other.

Anyhow, learned something here, it is a good InnerSource day :)

**Pull request merged**
