### PR TITLE
Added new Supporter

### PR DESCRIPTION
**Pull request by clcoffey**
I added Sourcegraph as a new supporter and to the InnerSource in Action Page.

### CODE REVIEW

**Review by spier — APPROVED** [review]
LGTM

**Comment by voborgus** [comment]
hi @clcoffey! Merge conflicts should be resolved before merging this to the main branch. Please ping me if you'll need help on that.

**Comment by clcoffey** [comment]
I just saw the conflicts now but they seem to be inside the logo file. I am not too sure what to do with that. It's the file I got from the company. I can try and get a .png file instead.

**Comment by clcoffey** [comment]
I think I know what the problem was, I uploaded the same file in my last 2 pull requests. I hope deleting the file fixed it.

**Review by claredillon — APPROVED** [review]
Thanks so much @clcoffey - brilliant to see another supporter added!! :)

**Pull request merged**
