### PR TITLE
French Language Support 🇫🇷

### PR DESCRIPTION
**Pull request by yuhattor**
# French Language Support

The InnerSource Commons (ISC) website is available in multiple languages. We appreciate your help in translating the site to make it accessible to French speakers.

Please keep in mind followings:

- Before beginning your translation, please read the [**i18n.md**](i18n.md) file for information on tools and processes.
- Do not edit or create any files under `content/en/learn/learning-path/`. These files are sourced from another repository and are not stored in the innersourcecommons.org repository. If you want to add or edit a language, please do so in the learning-path repository.
- Please do not include any untranslated files in your pull request (PR). Missing files will be automatically added from `content/en` at build time.

## The conditions for merging are as follows

- [ ] Website-mainterners Approval
- [ ] Native check
	While machine translation can be useful for large volumes of text and can serve as a starting point for translation, it can also produce unprofessional results. In addition, since machine translation can be used by anyone with a browser extension, this translation project requires a more professional level
- [ ] At least 50% of the files in the "Files to be translated" section should be translated

## Files to be translated

The following is a list of files that should be translated first. It is a good idea to translate from here, but you are not required to follow it.

**Setting files**

- [ ] i18n/fr.yaml
- [ ] config/_default/menus.fr.yaml

**Content files**

- [ ] content/fr/about/announcements/_index.md
- [ ] content/fr/about/_index.md
- [ ] content/fr/about/sponsors.md
- [ ] content/fr/about/members.md
- [ ] content/fr/about/board/_index.md
- [ ] content/fr/about/codeofconduct.md
- [ ] content/fr/about/contact.md
- [ ] content/fr/community/_index.md
- [ ] content/fr/community/services.md
- [ ] content/fr/events/_index.md
- [ ] content/fr/_index.md
- [ ] content/fr/learn/_index.md
- [ ] content/fr/learn/books/managing-innersource-projects.md
- [ ] content/fr/learn/books/innersource-patterns.md
- [ ] content/fr/learn/books/_index.md
- [ ] content/fr/learn/books/adopting-innersource-principles-and-case-studies.md
- [ ] content/fr/learn/books/understanding-the-innersource-checklist.md
- [ ] content/fr/learn/books/getting-started-with-innersource.md
- [ ] content/fr/learn/patterns.md
- [ ] content/fr/learn/research/state-of-innersource-survey-2021.md
- [ ] content/fr/learn/research/state-of-innersource-survey-2016.md
- [ ] content/fr/learn/research/_index.md
- [ ] content/fr/learn/research/state-of-innersource-survey-2020.md
- [ ] content/fr/redirects/patterns.md
- [ ] content/fr/stories/_index.md
- [ ] content/fr/stories/microsoft.md

### CODE REVIEW

**Comment by yuhattor** [comment]
Just a heads up, this is a tutorial video:)

[Contribute to innersourcecommons.org in Your Language](https://www.youtube.com/watch?v=gWXUgYIpJqg)

**Comment by tfroment** [comment]
Thanks @yuhattor currently working on it in my forked branch at https://github.com/tfroment/innersourcecommons.org/tree/i18n-fr, I expect to have finished all the files you mentionned here by the end of this week

**Comment by tfroment** [comment]
Hi @yuhattor : translation of this first list of files is DONE (and commited) in my forked local branch at https://github.com/tfroment/innersourcecommons.org/tree/i18n-fr

I don't want to make any mistake from now: 
Shal I use the codespace option as below ?
image

or shall I use the PR option from my local branch ? like this:
image

Thanks for your help and apologize for this dummy question ;-)

**Comment by yuhattor** [comment]
@tfroment 
wow, very quick!!
Thank you for your contribution!!

You can edit your PR in any way you like, even after you have created it.
Generally, after you commit your environment to your repository, you can send a pull request from your browser. So, both of the methods in the two screenshots look correct.

**Comment by tfroment** [comment]
Hi @yuhattor thank you for your answer: I understand the first screen is a way to edit the existing PR, but from now, I am note 100% sure of what I am allowed to do:
- shall I merge my code from (tfroment) local branch to i18n-FR branch or does it go through a separate PR ? or the same PR (this one here) ? I am a bit confused at this step

**Comment by yuhattor** [comment]
Taken offline, but I will provide a summary of the steps involved

The steps are supposed to be below

1. create a PR for i18n-fr. For example, send me a request to merge the tfroment/i18n-fr branch into the [innersourcecommons.org/i18n-fr](http://innersourcecommons.org/i18n-fr) branch and I’ll merge this right in. Initially, this will be done by website-maintainer. I recently became a website-maintainer myself, and I think Dmitrii can do this as well.
2. complete i18n-fr to a publishable level.
3. native reviews. This is something website-maintainer cannot do. If possible, we would like to have a native French speaker look at the changelog and review it.
3. merge i18n-fr into master. This will be done by website-maintainer after the native review is done.
Once merged to master, the master will receive PRs about French changes directly from the master, not from the i18n-fr branch. We will create a role like “i18n-maintainer” which is a maintainer role in i18n and invite people to manage it. We will need some initial review, including onboarding, but we think we need a contributor like yourself to take on that role as it will be hard for website-maintainer to review each language change after it has been merged into production. I think we need a contributor like yourself to take on that role. This is not a decision as I am in the process of discussing this with Dmitrii and other members, but I think it will happen.

This needs to be documented somewhere, I think. I’ll try to put it together when I have some free time.

**Comment by yuhattor** [comment]
Before merging this branch, I would like to address the menu design issue #432
This has been partially fixed in that issue, but it seems that it was not fundamentally fixed...

image

**Comment by yuhattor** [comment]
fyi: The linkcheck error will be addressed in the PR #464

**Comment by yuhattor** [comment]
merged #432 into i18n-fr and fixed the menu design misalignment.

image

**Comment by yuhattor** [comment]
I checked the French version and confirmed that it is possible to merge 👍

**Pull request merged**
