### PR TITLE
adding video to Mar 21st event

### PR DESCRIPTION
**Pull request by OliveCannon**
Adding video to March 21st event

Hi Yuki, 

i hope you are well!
I still don't have anyone that I can assign changes too.  If you know of someone can you send me their details.  Sorry to keep asking you!

Many thanks, 
Olive

### CODE REVIEW

**Comment by spier** [comment]
@OliveCannon when you file a new PR like this, the @InnerSourceCommons/website-maintainers team is automatically assigned to the PR. They will receive notifications about this. So in theory you should not have to assign anybody.

Plus, most open source communities work in a "pull model" i.e. when people have time they will pick a task themselves, rather than somebody else assigning a task to them.

Is your experiences that it takes too long to get your PRs merged, or where does the desire to assign somebody to the PR come from?

**Comment by OliveCannon** [comment]
Hi Sebastian, 

When I started to do this work I was informed that it would be best to assign a specific person.  I am happy not to assign anyone if this is preferable.

thanks,
Olive

**Comment by spier** [comment]
@OliveCannon I see. Personally I would consider such assignments an anti-pattern in the open source context. I am not sure though.

Given that this PR did not receive a review since a week or so, maybe our current process is a bit broken?

Anyhow, I will review (and likely merge) this PR now. Could you please confirm if your change looks ok in production?

**Review by spier — APPROVED** [review]

**Comment by OliveCannon** [comment]
Hi Sebastian,

I am having a problem seeing my changes on the localhost and would really appreciate it if you have a moment to go through this with me. 

many thanks, 
Olive

**Comment by spier** [comment]
@OliveCannon I am no expert with our hugo system either but I can try to help you tomorrow.
Please find me in Slack and we can see how far we get.

You should see see all merged PRs on https://innersourcecommons.org/ now though.
(I had to fix something with our deployment)

**Pull request merged**
