### PR TITLE
Google Indexing

### PR DESCRIPTION
**Pull request by clcoffey**
Adding Google Verification file to the website.

If this is ever removed we will loose the verification from Google.

### CODE REVIEW

**Comment by lenucksi** [comment]
We can also add our domains as "domain property" by means of a DNS TXT entry that will grant us verification on all subdomains. @cewilliams can do this. See here: https://support.google.com/webmasters/answer/34592?hl=en

**Comment by clcoffey** [comment]
I know, I just didn't have access to it so I chose this route. More than
happy to go that way though.

**Comment by cewilliams** [comment]
Let's go with the DNS route. @clcoffey would you please generate the TXT record and share it via slack?

**Comment by clcoffey** [comment]
Here is the code for the DNS
google-site-verification=VUVix1JHxfGmR8StDjdSnwD8wOGgQCkOnJBWWKeUh4U 

Screenshot 2021-03-22 at 09 35 11

**Comment by lenucksi** [comment]
Just as a side note: Bing Webmaster tools accept Google DNS verification, create an account, say it's Google verified, be happy. Yandex needs their own DNS entry, otherwise completely same. Don't know about Chinese or japanese search engines but I'm sure they'll have something similar.

**Comment by clcoffey** [comment]
That's brilliant! Thanks for that Johannes!

**Comment by cewilliams** [comment]
DNS updated.

**Pull request closed without merging**
