### PR TITLE
Create Summit CFP page

### PR DESCRIPTION
**Pull request by clcoffey**
I created the page and text for the ISC Summit CFP (related to https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/100)

Still needs a new banner and logo and the publishing date updated to Sept 1st.

### CODE REVIEW

**Comment by clcoffey** [comment]
@voborgus let me know when we have an updated Logo for the summit to create the banner for the page.

**Comment by voborgus** [comment]
@clcoffey new logo for the summit [here](https://drive.google.com/drive/u/0/folders/1UNj5fmhtdLPcgPBToBisE0SGXgnQBxAD).

**Comment by clcoffey** [comment]
@voborgus thank you!
@claredillon do you want to create the banner or do you want me to give it a try?

**Comment by clcoffey** [comment]
Final version of the page looking like this: 
screencapture-localhost-1313-events-isc-2021-2021-08-31-14_10_22

**Review by claredillon — APPROVED** [review]
Looks good to me!

**Pull request merged**
