### PR TITLE
Adding description of ISPO WG

### PR DESCRIPTION
**Pull request by spier**
This PR adds the following to the `/community` page.

Screenshot 2023-02-15 at 13 13 56

### CODE REVIEW

**Comment by spier** [comment]
By adding this new section, I also pushed the description of the Board further down.
I also moved the ISC logo used for the Board to the left, as it looks like we also want images to be alternating between left and right on this page?

Minor issue: 
The spacing between ISC logo and the description of the board seems too little, doesn't it?
I could not figure out how to change that with bootstrap styles.

See screenshot below.
Screenshot 2023-02-15 at 13 08 44

@voborgus any idea how to fix this? Or should I just leave it as is?

**Review by rrrutledge — APPROVED** [review]
Thank you ❗

**Comment by spier** [comment]
@voborgus I was itching to see this live, so I merged the PR already.

If you have any idea for how to fix the [issue described above](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/478#issuecomment-1431281480) I would love to hear it though.

**Comment by rrrutledge** [comment]
Thank you, @spier ❗️

**Pull request merged**
