### PR TITLE
Fix filename for i18n.md

### PR DESCRIPTION
**Pull request by spier**
I wanted to read how the i18n Support works.

When clicking on on the `i18n.md` file in the GitHub UI, I noticed that the URL is this i.e. a space prefixed in front of the name. The URL of the file currently is `https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/%20i18n.md`.

The link from the main README to that file didn't work either.

I fixed this by stripping the space in front of the filename.

### CODE REVIEW

**Comment by spier** [comment]
@yuhattor I suspect that space in front of the name was just a mistake?

**Comment by yuhattor** [comment]
Oh, that's my bad! Thanks!

**Review by yuhattor — APPROVED** [review]

**Comment by yuhattor** [comment]
@InnerSourceCommons/website-maintainers 
Please merge this PR:)

**Comment by spier** [comment]
As this was a trivial change, I merged this myself.

**Pull request merged**
