### PR TITLE
Update broken link for github article

### PR DESCRIPTION
**Pull request by zkoppert**
The previous link rendered a 404 so I believe this article is a good replacement.
Screen Shot 2022-04-14 at 12 41 20 PM

Thanks @snsinahub for finding this issue!

### CODE REVIEW

**Review by snsinahub — APPROVED** [review]
LGTM

**Review by spier — APPROVED** [review]
LGTM

**Comment by spier** [comment]
@zkoppert approved and merged.
I believe it will auto-deploy but we will know shortly :)

As an aside:
Do you know what happened to the `infocus.github.com`? 
Is it that a new event is coming up and the old sessions/articles get purged?

**Comment by spier** [comment]
And yes it worked. New article is live.
Thanks for the fix!

**Comment by zkoppert** [comment]
@spier there is a new event and every quarter or so the old videos get purged.

**Pull request merged**
