### PR TITLE
Update to ISC Board for 2022

### PR DESCRIPTION
**Pull request by spier**
Update to the Board page on our website with the new ISC Board for 2022:
https://innersourcecommons.org/about/board/

### Todo:

- [x] adding pic and bio for new Board members
- [x] list previous Board members in a "history" section to show our appreciation for their work - also see ASF [example](https://www.apache.org/foundation/board/)
- [x] reduce image size of profile pictures
- [x] some layout improvements for the profile images
- [x] (stretch goal) give images a more cohesive look
- [ ] get updated picture for some board members (to get a good quality picture into the now fixed 300x300 frame)

### Out of scope:

Listing all officers, as they haven't been determined .

### CODE REVIEW

**Comment by spier** [comment]
Useful resource for styling the images in a more cohesive look:
https://www.webascender.com/blog/use-css-image-filters-create-cohesive-look-feel-website/

**Comment by spier** [comment]
@voborgus one question about the bootstrap grid if I may:
I understood that each Grid row has a maximum of 12 columns that I can use, right?

I changed the layout of our Board page, and I don't know how to check whether I used too many columns.
I think I am using `col-md-3 + col-md-8 + offset-md-1` => so that would be 12 columns in total, correct?

Also is there any other way to check myself whether I configured a Grid row correctly?

Thanks for your help.

**Comment by spier** [comment]
I am still reaching out to a couple of the Board members to get updated pictures. So this branch should not be merged yet.
But if anybody has time to do a review of the general idea here, please go ahead :)

**Comment by clcoffey** [comment]
I love the new styling Sebastian! It looks much more consistent and professional. Thanks for taking the time to do this!

**Comment by spier** [comment]
@clcoffey this is now ready for review and merging.

Some Board members might still provide updated pictures but those can be added in new PRs then.

**Review by voborgus — APPROVED** [review]
thanks for the PR

**Comment by voborgus** [comment]
https://innersourcecommons.org/about/board/ live on the site now

**Comment by spier** [comment]
Awesome, thank you @voborgus !

**Pull request merged**
