### PR TITLE
Board update: Change title Sebastian (VP)

### PR DESCRIPTION
**Pull request by spier**
- Change title Sebastian (VP) - FYI I opted to remove the "Assistant Secretary" title for me. Found it confusing to have two roles/titles there and is not a mandatory role anyways.
- Reorder to move officers to the top.

### CODE REVIEW

**Comment by MaineC** [comment]
> Reorder to move officers to the top.

I find this confusing to the uninitiated reader, as officers report to the board of directors.

It makes more sense to keep board members in alphabetical order (by first or last name), and list elected officers and VPs below.

**Comment by spier** [comment]
> > Reorder to move officers to the top.
> 
> I find this confusing to the uninitiated reader, as officers report to the board of directors.
> 
> It makes more sense to keep board members in alphabetical order (by first or last name), and list elected officers and VPs below.

Does that mean you would liste people twice that are board members as well as officers?
(applies to you, Daniel, Tom, me)

Further one might argue that an uninitiated reader would not know that the "officers report to the board of directors". :)

This can go either way for me, I really don't mind.
I don't know what the most important purpose of this page for the readers is, so don't have anything that I can judge our implementation against.

**Comment by voborgus** [comment]
Just for the context: when we added titles on this page some time ago, we break the alphabetical order. So, Sebastian's change not brings anything new on that field there :)

**Review by voborgus — APPROVED** [review]

**Comment by MaineC** [comment]
If we do list roles, I'd at least make sure all roles are listed.

We could either keep the current format, or now that we have individuals with multiple roles, we could instead add a table below the directors that lists first role, second name.

Wrt. uninitiated not knowing reporting structure, that's what the other issue I filed is about - essentially make it easier for those who aren't into reading bylaws to understand how we operate. Also because in some aspects we are intentionally different from other orgs.

**Comment by spier** [comment]
@MaineC thanks for the feedback. Let's try to find an iteration that works for now, and then do further improvements whenever anybody has more time.

> If we do list roles, I'd at least make sure all roles are listed.

We are already listing all roles, are we not?
The only one I left away was my Assistant Secretary role, as it isn't even required by our bylaws.

> We could either keep the current format, or now that we have individuals with multiple roles, we could instead add a table below the directors that lists first role, second name.

For now I suggest that we keep the formt that we have, as otherwise this PR will linger for a while.

Eventually I would like to try a completely different layout for this page, as there is so much scrolling required right now.
I am thinking more a matrix with all faces/names/roles and only when you hover/click the face you get the details for the person. Unfortunately I don't have time to work on this right now.

> Wrt. uninitiated not knowing reporting structure, that's what the other issue I filed is about - essentially make it easier for those who aren't into reading bylaws to understand how we operate. Also because in some aspects we are intentionally different from other orgs.

For this point, could you try a separate PR yourself at a later point? I don't know exactly what you are after here, so I would have a hard time implementing it.

**Comment by spier** [comment]
Technically I could already merge this as the PR has one approval but given @MaineC 's comments I feel like waiting for her confirmation is best.

**Comment by MaineC** [comment]
> The only one I left away was my Assistant Secretary role, as it isn't even required by our bylaws.

If we are aiming for a minimal change, I'd leave the information up that you are filling that role, even if it's not required by our bylaws - it's still a role that we have.

> For this point, could you try a separate PR yourself at a later point? I don't know exactly what you are after here, so I 
> would have a hard time implementing it.

That's why I moved that observation to an issue elsewhere - nothing to tackle here, but also something we must do.

**Comment by spier** [comment]
I added the Assistant Secretary in again.

Will merge and deploy the changes now.

**Comment by spier** [comment]
I did not notice the other issue that @MaineC filed. But I think it is this one?
https://github.com/InnerSourceCommons/innersourcecommons.org/issues/622

**Comment by MaineC** [comment]
Yes, exactly.

**Pull request merged**
