### PR TITLE
Fix menu misalignment

### PR DESCRIPTION
**Pull request by yuhattor**
Fixed menu misalignment

**Before**
image
**After**
image

---
**Before** 
image

**After**
image

### CODE REVIEW

**Comment by yuhattor** [comment]
Added Japanese support
image
image

**Comment by voborgus** [comment]
Thanks for the change, looks amazing. My only concern is the fact that mobile menu takes the big part of the screen and hides the main content over the scroll.

What do you think about to leave the mobile menu horisontally and center the language and slack buttons?

**Comment by yuhattor** [comment]
@voborgus That may indeed be the case. Thanks for the comment!
I just think it's better than the current design, which is a bit broken, but what do you think?

I was actually trying to get the designs to line up well side by side, but it didn't work out so well. I think some drastic editing would be needed to change the menu, such as auto-sizing or making it two columns. That may be a future task.

**Comment by yuhattor** [comment]
The French support issue has required some design modifications to the menu, so I will try to apply this one that is currently working for once.
If we run into problems in the future, or if there is still demand for a side-by-side arrangement, we would like to revert back. This may be an issue that should be considered for an ongoing redesign.

**Pull request closed without merging**
