### PR TITLE
aligns the buttons and images in the Events page across all cards

### PR DESCRIPTION
**Pull request by andrea-kyurchiev**
Issues addressed: 
#198

### CODE REVIEW

**Review by voborgus — APPROVED** [review]
thanks a lot!

**Comment by spier** [comment]
@andrea-kyurchiev thanks for doing this work.

Could you list what the exact UI changes were that you implemented with this change?
If you could share an annotated screenshot, that would make it the easiest for me.

I am wondering about this because I see a couple of things on https://innersourcecommons.org/events/ that look odd now, and I  wonder if any of them might be regressions from this PR.

**Comment by andrea-kyurchiev** [comment]
@spier you can see all changes in the "Commits" tab of the PR
See attached: 
image


image

**Comment by spier** [comment]
hehe, yeah, I know the Commits tab :)

What I meant rather was what the intended UI changes were.

It might be easier when I file a new issue, where I can provide examples from the events page, that show which pieces might be broken now. Then we can take it from there.

**Pull request merged**
