### PR TITLE
refactor: makes changes to the about section

### LINKED ISSUE #320: Update Vision and Mission Statements on the website
This page: https://innersourcecommons.org/about/

image

New Vision Statement:

> The InnerSource Commons is a thriving community that empowers organisations and people worldwide to apply and gain the benefits of open collaboration in their internal work.

New Mission Statement:

> We empower developers and organisations to apply open collaboration principles in their daily work.
> 
> We are the neutral hub and central collaboration space for InnerSource knowledge. As such, we maintain our independence and operate on a lean budget.
> 
> We build a strong, inclusive community and industry partnerships. Together, we apply open collaboration principles to drive the conversation about InnerSource and steward the InnerSource body of knowledge.
> 
>

### PR DESCRIPTION
**Pull request by andrea-kyurchiev**
Closes https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/320

image

image

### CODE REVIEW

**Review by rrrutledge — APPROVED** [review]
Thank you!

**Review by CiaraFlanagan — APPROVED** [review]

**Comment by CiaraFlanagan** [comment]
@rrrutledge, I've just merged this.

**Comment by CiaraFlanagan** [comment]
@andrea-kyurchiev 

Do I need to check in with the #local communities to ask about translating this page?

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan yes that might be useful as it seems to not be translated for any of the languages

**Comment by rrrutledge** [comment]
We need a way to systematize this happening for ongoing updates to the web page.

**Comment by spier** [comment]
> We need a way to systematize this happening for ongoing updates to the web page.

How do you imagine this to happen?

There are already auto-generated issues like this on this repo, so I assume you need something more than this?
https://github.com/InnerSourceCommons/innersourcecommons.org/issues/735

As the translations are happening by volunteers, we cannot really guarantee a "quick" translation of the original English content to the other 3 languages (Japanese, Portuguese, French).

So part of a system around this should be a decision about "what needs to be translated, and what not". This would at least reduce the required work a bit.

**Comment by rrrutledge** [comment]
Wow - that's 🆒.  I didn't know about the auto-generated issues.  Maybe on some schedule we go and check these and bring them into alignment.  The first check could be from @andrea-kyurchiev to see if it is even a translation needed.  It looks like all of the items in that issue are just HTML syntax etc that don't even need translation.

**Comment by CiaraFlanagan** [comment]
Hey @spier and @rrrutledge 

I'm glad to see this conversation happening. 

@spier are there autogenerated issues on the repo for the Brazilian Portuguese and Japanese versions too when there are updates?

Our volunteers are busy people and I'm wondering if there's anything that can be done differently to support them in some way ... 

@andrea-kyurchiev - did you mention once that you try to run new content through google translate for the other language versions of the website?  Can you tell us more about what happens at your end?

**Comment by CiaraFlanagan** [comment]
@fer-correa @yuhattor @tfroment 

I'm adding you to this conversation in case there is anything that you would like to add ...

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan if I am making changes to pages that are present in translations I run the changes through google translate and try to get the translations reviewed by the native speakers in the organisation.

**Comment by fer-correa** [comment]
Hi @andrea-kyurchiev , 
About reviewing the content in Brazilian Portuguese, if you need help don't hesitate to let me know.
I understand that there are Brazilians working with you and supporting you in this review, right? But if you still see a need, I'm here to help 😃.

**Pull request merged**
