### PR TITLE
Fix typos in "Implementing InnerSource Metrics"

### PR DESCRIPTION
**Pull request by spier**
@OliveCannon @yuhattor this is fixing typos from #483

### CODE REVIEW

**Comment by yuhattor** [comment]
@OliveCannon It looks like you intentionally wrote the title of the session, can you please confirm this?

**Comment by spier** [comment]
Even if you want to keep the capitalization of the title, there is still a typo in "Metrics".

**Comment by OliveCannon** [comment]
Fixed

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Sebastian Spier ***@***.***>
Sent: Sunday, February 19, 2023 8:11:13 AM
To: InnerSourceCommons/innersourcecommons.org ***@***.***>
Cc: OliveCannon ***@***.***>; Mention ***@***.***>
Subject: [InnerSourceCommons/innersourcecommons.org] Fix typos in "Implementing InnerSource Metrics" (PR #484)


@OliveCannon<https://github.com/OliveCannon> @yuhattor<https://github.com/yuhattor> this is fixing typos from #483<https://github.com/InnerSourceCommons/innersourcecommons.org/pull/483>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/InnerSourceCommons/innersourcecommons.org/pull/484

Commit Summary

  *   cefb2c1<https://github.com/InnerSourceCommons/innersourcecommons.org/pull/484/commits/cefb2c10691b7f72fc483e5c7435dabe50d3962d> Fix typos in "Implementing InnerSource Metrics"

File Changes

(1 file<https://github.com/InnerSourceCommons/innersourcecommons.org/pull/484/files>)

  *   M content/en/events/meetup-2023-03-08.md<https://github.com/InnerSourceCommons/innersourcecommons.org/pull/484/files#diff-bf381f6ee12f66d6eba752925604550d043158e9c467607c01d14badb96a09c2> (2)

Patch Links:

  *   https://github.com/InnerSourceCommons/innersourcecommons.org/pull/484.patch
  *   https://github.com/InnerSourceCommons/innersourcecommons.org/pull/484.diff

**Review by yuhattor — APPROVED** [review]
Thanks, I got it. I merge @spier's change once to fix the typo first
@OliveCannon Thanks for another PR #486, But it looks like there are some files in there that we don't want, can you check them out? If you'd like to capitalize it, could you update that PR?? 👀

**Comment by OliveCannon** [comment]
thanks for doing this Yuki.

**Pull request merged**
