### PR TITLE
Join Mailing List

### PR DESCRIPTION
**Pull request by clcoffey**
I am trying to add the Join mailing list call to action further up on the Home page. To replace the call to action to complete the survey.

I need some help with styling the email field and subscribe button. Add some space between the field and the button.
image

### CODE REVIEW

**Comment by clcoffey** [comment]
@voborgus can you help with this by any chance?

**Comment by voborgus** [comment]
Sure, will have a look

**Comment by voborgus** [comment]
image
What about this?

**Comment by clcoffey** [comment]
It looks good. Thanks Dmitrii!

**Comment by clcoffey** [comment]
Do we need @claredillon to approve the pull request?

**Review by voborgus — APPROVED** [review]

**Pull request merged**
