### PR TITLE
Link directly the #virtual-coffee-buddies Slack

### PR DESCRIPTION
**Pull request by jeffabailey**

### CODE REVIEW

**Comment by jeffabailey** [comment]
This link fails.

https://www.chathamhouse.org/about-us/chatham-house-rule

It loads in a browser, but curl returns a 403.

```
curl -s -I https://www.chathamhouse.org/about-us/chatham-house-rule | head -n 1
HTTP/2 403
```

Is it a candidate for exclusion in Action?

Add it here?

https://github.com/jeffabailey/innersourcecommons.org/blob/patch-1/.lycheeignore

**Comment by spier** [comment]
@jeffabailey thanks for these improvements.

To your question:
Yes, `.lycheeignore` is where you should put the URL that you want to ignore.

I have seen the situation you describe happen sporadically as well.
Sometimes the URLs only fail only temporary, sometimes permanently.

So by all means, go ahead and add the URL to the ignore list.

**Review by rrrutledge — APPROVED** [review]
LGTM

**Comment by jeffabailey** [comment]
Linkchecker is now passing after adding the URL.

**Review by rrrutledge — APPROVED** [review]

**Review by spier — APPROVED** [review]

**Comment by spier** [comment]
@jeffabailey thanks for adding the link!

This should be live on https://innersourcecommons.org/community/ shortly.

**Pull request merged**
