### PR TITLE
Add nifty story

### PR DESCRIPTION
**Pull request by yuhattor**
This pull request includes changes to the `content/en/stories/_index.md`, `content/fr/stories/_index.md`, and `content/ja/stories/_index.md` files. The changes add a new company, "nifty", to the list of companies in each of these files. 

Addition of new company:

* <a href="diffhunk://#diff-1e8776b0ec62524efd28bacf5c55fcb0aa3911460b32c40947ef490f4404988dR175-R176">`content/en/stories/_index.md`</a>: Added a new company "nifty" with its logo, video link, article link, and author names.
* <a href="diffhunk://#diff-70173a5f4aa682e8545badf952cc19185252f8887338fbeb4e7a0588a3835affR175-R176">`content/fr/stories/_index.md`</a>: Added the same company "nifty" with its corresponding details in the French version of the file.
* <a href="diffhunk://#diff-790d3394b087fb1d449526995a1206b2ec449e9f7c8c4ba12178b212611f5d43R175-R176">`content/ja/stories/_index.md`</a>: Included the "nifty" company details in the Japanese version of the file as well.

### CODE REVIEW

**Comment by yuhattor** [comment]
@rashikawat If it's okay, please confirm and approve it (For approval, please give me a 👍 emoji)

**Review by spier — APPROVED** [review]
@yuhattor I think if you have evidence of the use of InnerSource practices, as well as confirmation from the org that they are happy to be listed, then that is all you need to publish a story.

Thank you for adding these stories from Japan!

**Comment by yuhattor** [comment]
@spier Thank you! 
Then Nifty would have already fulfilled it. It has been approved by @rashikawat, Nifty's person in charge,  and the article is full of InnerSource evidence :)

I will merge it

**Comment by spier** [comment]
And it is live 🥳 

Screenshot 2023-12-13 at 14 44 58

**Pull request merged**
