### PR TITLE
Fixing #500

### PR DESCRIPTION
**Pull request by tfroment**
Fixing https://github.com/InnerSourceCommons/innersourcecommons.org/issues/500

- Change name of George in Members in FR page
- Add new Story in FR Stories page
- Add new ISPO Working Group in Community page

### CODE REVIEW

**Comment by tfroment** [comment]
Wao, link checker failed du to " `set-output` command "https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

I have no idea how to fix that @yuhattor, I just translated some existing pages so I don't catch why this error occurs now

**Review by spier — APPROVED** [review]
LGTM

**Comment by spier** [comment]
@tfroment I approved and merged the PR.

Could you confirm on PROD that this looks as expected?
And if yes, can you close #500? (assuming that you have those permissions)

**Comment by tfroment** [comment]
> @tfroment I approved and merged the PR.
> 
> Could you confirm on PROD that this looks as expected? And if yes, can you close #500? (assuming that you have those permissions)

This is OK on PROD. Thank you for reviewing @spier 
I don't have permission to close #500

**Pull request merged**
